FROM rust:1-slim-bookworm AS rust-builder

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    pkg-config

FROM rust-builder AS builder-edge

WORKDIR /build
COPY kafka-edge-bin .
RUN cargo build --release

FROM docker.io/bitnamilegacy/kafka:3.4

USER root

WORKDIR /

RUN mkdir kafka-edge-bin/

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    pkg-config \
    vim \
    git \
    curl

## Update new packages
RUN apt-get update

# Build edge
COPY --from=builder-edge /build/target/release/kafka-edge-rs /kafka-edge-rs
# Copy config file
COPY ./kafka-rs-configs/kafka_edge_config-edge.toml /kafka_edge_config.toml

# Copy startup script
WORKDIR /
COPY ./docker-startup-scripts/startup-edge.sh /startup.sh
RUN chmod +x /startup.sh
