FROM rust:1.72.0-slim as builder

WORKDIR /usr/src/kafka-edge-rs
COPY kafka-edge-bin .
RUN cargo install --path .

WORKDIR /usr/src/kafka-producer-rs
COPY kafka-producer-rs .
RUN cargo install --path .

FROM docker.io/bitnami/kafka:3.4

USER root

WORKDIR /

# Copy binaries
COPY --from=builder /usr/local/cargo/bin/kafka-edge-rs .
COPY --from=builder /usr/local/cargo/bin/kafka-producer-rs .

RUN apt-get update
RUN apt-get install -y \
    build-essential \
    libssl-dev \
    pkg-config \
    vim

# Copy data files
COPY data/china /data/china

# Copy config files
COPY ./kafka-rs-configs/producer_config.toml /kafka-producer-rs/producer_config.toml
COPY ./kafka-rs-configs/kafka_edge_config-kafka.toml /kafka_edge_config.toml

# Copy startup script
WORKDIR /
COPY ./docker-startup-scripts/startup-kafka.sh /startup.sh
RUN chmod +x /startup.sh
