FROM docker.io/bitnamilegacy/spark:3.3

USER root

WORKDIR /

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libssl-dev \
    pkg-config \
    git \
    vim \
    curl && \
    pip install notebook

# Setup flask web app
COPY flask_data_viz /flask_data_viz
WORKDIR /flask_data_viz
RUN pip3 install -r requirements.txt

WORKDIR /
