FROM rust:1.73.0-bullseye as builder

WORKDIR /usr/src/kafka-edge-bin
COPY kafka-edge-bin .
RUN cargo install --locked --path ./kafka-edge-rs

FROM docker.io/bitnami/kafka:3.4

USER root
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    pkg-config \
    vim

USER 1001

COPY --from=builder /usr/local/cargo/bin/kafka-edge-rs .

COPY data/china/neighborhood/shenzhen_converted.geojson data/china/neighborhood/shenzhen_converted.geojson

# Copy config file
COPY ./kafka-rs-configs/kafka_edge_config-edge.toml kafka_edge_config.toml

# Copy startup script
COPY ./docker-startup-scripts/startup-edge.sh startup.sh
