FROM rust:1.76.0-slim-buster AS builder

RUN apt-get update -y && \
  apt-get install -y pkg-config libssl-dev

ENV OPENSSL_DIR=/usr/include/openssl \
  OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu \
  OPENSSL_INCLUDE_DIR=/usr/include/openssl

WORKDIR /kafka-producer-rs
COPY kafka-producer-rs .

RUN cargo build --release


FROM gcr.io/distroless/base:nonroot-arm64

WORKDIR /home/nonroot
USER nonroot
ENV LIB_DIR_PREFIX aarch64

# Copy shared libraries into distroless base.
COPY --from=builder /lib/${LIB_DIR_PREFIX}-linux-gnu/libgcc_s.so.1 /lib/${LIB_DIR_PREFIX}-linux-gnu/

COPY --from=builder --chown=65532:65532 /kafka-producer-rs/target/release/kafka-producer-rs ./kafka-producer-rs
COPY --chown=65532:65532 ./kafka-rs-configs/producer_config.toml ./producer_config.toml

ENTRYPOINT [ "/home/nonroot/kafka-producer-rs" ]
