apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kafka
  name: kafka
spec:
  ports:
    - name: "9092"
      port: 9092
      targetPort: 9092
  selector:
    app.kubernetes.io/name: kafka
