apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: spark
  name: spark
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "4040"
      port: 4040
      targetPort: 4040
    - name: "7077"
      port: 7077
      targetPort: 7077
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    app.kubernetes.io/name: spark
