apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spark-worker
  name: spark-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-worker
    spec:
      automountServiceAccountToken: false
      containers:
        - env:
            - name: SPARK_EXECUTOR_MEMORY
              value: 1G
            - name: SPARK_MASTER_URL
              value: spark://spark:7077
            - name: SPARK_MODE
              value: worker
            - name: SPARK_WORKER_CORES
              value: "2"
            - name: SPARK_WORKER_MEMORY
              value: 1G
          image: docker.io/bitnami/spark:3.3
          name: spark-worker
          resources:
            limits:
              cpu: "2"
              ephemeral-storage: "1Gi"
              memory: "4Gi"
            requests:
              cpu: "2"
              ephemeral-storage: "512Mi"
              memory: "4Gi"
          volumeMounts:
            - mountPath: /vol
              name: spark-worker-claim0
      restartPolicy: Always
      volumes:
        - name: spark-worker-claim0
          persistentVolumeClaim:
            claimName: spark-worker-claim0
