[kafka]
zookeeper = [ "zookeeper:2181" ]
brokers = [ "localhost:9092" ]
topic = "datain"
partitions = 2

[data]
source = "/data/china/mobility/guang.csv"
msg_sleep_in_ms = 1
chunk_size = 1000
chunk_sleep_in_ms = 500
